/** The 27 Nakshatras (birth stars). Keep in sync with the mobile app. */
export const NAKSHATRAMS = [
  'Ashwini',
  'Bharani',
  'Kruthika',
  'Rohini',
  'Mrughasira',
  'Aarudra',
  'Punarvasu',
  'Pushya',
  'Ashlesha',
  'Maka',
  'Purva Phalguni',
  'Uttara Phalguni',
  'Hasta',
  'Chita',
  'Swathi',
  'Vishakha',
  'Anuradha',
  'Jyeshtha',
  'Mula',
  'Purva Ashadha',
  'Uttara Ashadha',
  'Sravana',
  'Dhanishta',
  'Shatabhisha',
  'Purvabhadra',
  'Uttarabhadra',
  'Revati',
] as const
